db:
  build: ./dockerfiles/postgres-9.4
  ports:
    - "5432"
  volumes:
    - db_backups:/var/lib/postgresql/db_backups
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
